FROM golang:1.19 as builder
WORKDIR /opt/controller

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o log-controller cmd/controller/main.go

FROM alpine
WORKDIR /opt/controller/
COPY --from=builder /opt/controller/log-controller log-controller
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone
ENTRYPOINT [/opt/controller/log-controller]
